### ISSUE TITLE
Chrome/Chromium

### ISSUE THREAD

**Issue by GuillaumeAmat** [ekino/docker-buildbox#125]
Hi there!

In order to run some e2e and perf tests I have the need of an image which includes at least one internet browser. Chrome/Chromium seems to be the obvious one as Lighthouse (the perf checker tool I want to use) is based on it.

What do you think about that? Would you consider a PR on the subject?

**Comment by mremi** [comment]
Hi @GuillaumeAmat ,

What do you think about https://github.com/SeleniumHQ/docker-selenium?

**Comment by GuillaumeAmat** [comment]
I tried it but it misses a lot of things to fill my needs. I'll try different options and come back with a solution.

**Comment by GuillaumeAmat** [comment]
I have a working Dockerfile and propose a PR soon.

In a nutshell, the image is based on an official Puppeteer recipe. I just switched the base image from `node:8-slim` to `ekino/docker-buildbox:latest-node10.10`.

That way we have all the usual Node buildbox tools, Chrome (for Lighthouse, Pwmetrics, etc.) and even Puppeteer.
