### ISSUE TITLE
Changelog.md

### ISSUE THREAD

**Issue by saugereau** [ekino/docker-buildbox#186]
What about generate changelog on release process (instead of add new line on each development) ?
@mremi , what is the current release process ? Is there any way to use something like https://pypi.org/project/gitchangelog/, to build and commit new Changelog.md during release process (maybe by travis) ?

**Comment by saugereau** [comment]
Current process is : 

- create a branch release
- update changelog.md
- commit 
- merge release branch

The longest part of the current process is rebasing each branch (of feature) to fix the CHANGELOG as you merge each branch one after the other.
As we don’t have a very frequent release process, usually we’ll merge all the feature branches in the days before releasing. Like this week for instance. We have 7 open PRs. So over the next week We need to merge PR1. Rebase PR2 ....
This would be less of an issue if we were merging more frequently

**Comment by Mallear** [comment]
I've found this tool, maybe useful : https://github.com/github-changelog-generator/github-changelog-generator

**Comment by saugereau** [comment]
I try something for this here : https://github.com/saugereau/github-actions-sample, any comment is welcome

**Comment by Mallear** [comment]
The process will be :
- create release/* branch
- merge
- tags master 
?
That sounds very nice :D

**Comment by clemstoquart** [comment]
Thanks @saugereau 

It's ok with me.

**Comment by saugereau** [comment]
> The process will be :
> 
> * create release/* branch
> * merge
> * tags master
>   ?
>   That sounds very nice :D

I confirm @Mallear :)

**Comment by Crow-EH** [comment]
I recommend https://github.com/TriPSs/conventional-changelog-action. It uses https://github.com/conventional-changelog/conventional-changelog under the hood.

They use it themselves, you can see it in their release workflow : https://github.com/TriPSs/conventional-changelog-action/blob/master/.github/workflows/release.yml

**Comment by axelpavageau** [comment]
I'll close this long standing issue, as github now automatically generates changelogs for new releases.
