### ISSUE TITLE
Drop Node 6 image

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#191]
Hi,

Node 6 has reached its scheduled end-of-life on April 30, 2019. I think it's safe that we stop building Node 6 images.

**Comment by Crow-EH** [comment]
We need to check if we have projects using it first I think.
Some tools need to be maintained if we don't want the CI to break (like when we introduced role-based authent in CI helper while dropping AWS credentials env vars from the runners).

Ping @rande @GuillaumeAmat

**Comment by rande** [comment]
@Crow-EH the failing jobs can also be update to match latest version of the buildbox.
