### ISSUE TITLE
Drop java 6 image

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#192]
Hi,

Java 6 has reached its end-of-life a long time ago. It doesn't seem useful to continue supporting it.

**Comment by Crow-EH** [comment]
We still have old projects using it, but I don't see any critical tool installed requiring us to maintain it until projects EOL (like ci helper).
Good for me. 👍

**Comment by mremi** [comment]
LGTM, moreover we can still use existing tags.
