### ISSUE TITLE
Migrate from alpine to debian + image clean

### ISSUE THREAD

**Issue by Mallear** [ekino/docker-buildbox#248]
From discussion started [here](https://github.com/ekino/docker-buildbox/pull/247#issuecomment-583001699), switching for Debian-based images instead of Alpine-based would be a great improvement, at least for all image used for python scripts/app.

Plus it will avoid random failing build caused by Musl lack of compatibility and resiliency.

I will start upgrading these images and clean them (I dont think ci-helper is needed on images only used by ops team).

**Comment by Mallear** [comment]
I think I could need some insight and thoughts on some topics:

- Does anybody use ci-helpers in any of the following images: ansible, arachni, aws, dind-aws, python ?

- I will base images on python:3-buster-slim. I think of managing an image with python 3.6, 3.7 and 3.8. This way every script will have a corresponding image. What are you thoughts ?

**Comment by clemstoquart** [comment]
Hi,

- I don't use ci-helpers on these images
- I don't know what's best here 🤷‍♂️

**Comment by Crow-EH** [comment]
* I don't know
* python buster-slim seems to be a great solution. We you say "every script will have a corresponding image", do you mean you want to build ansible, arachni, aws and dind-aws from ou own python image ?

**Comment by Mallear** [comment]
@Crow-EH I mean I will build a python 3.6, 3.7 and 3.8 image for each. This way we do not force everybody to work on the same python version. Tags will be something like `{tool_version}-p{python_version}-{date}`

**Comment by Crow-EH** [comment]
oh ok, you mean each image will be available in the three python versions. Fine by me then.

**Comment by Mallear** [comment]
Concerning Python 2.7, I'm guessing it is only used to interact with anchore. I'm deleting ci-helper from it. Can you confirm it's ok for you @mremi ?

Concerning other python images, I'm deleting pip and pipenv version fixes. These were needed when there was a non compatible version of pipenv.

**Comment by Mallear** [comment]
Hello,
I've open a PR #250 . I haven't rebased my commit yet as I think this will need to be discuss, at least naming convention. And I may have deleted CI Helper in too many image.

To go further, I would like to propose an alternative to the  dind-aws image, as we cannot control any version of used tool is this image (installing proper python 3.8 version on alpine is a pain).

A workaround to dind image could be the following:
- Sharing the docker socket of the VM running gitlab runners
- Installing docker binary in needed image
- Running docker inside the container linking to the host docker socket.

This way, containers will not be started in the runner's container but outside, on the same host. This seems to be the proper way to use docker-in-docker for CI purpose (based on [J. Petazzoni blog post](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) ).
This should be tested first, obviously.

**Comment by mremi** [comment]
The ci-helper is used for artifacts purpose between jobs/builds, GitLab supports a cache system as well but I think it doesn't match yet exactly what we expect (see https://docs.gitlab.com/ee/ci/yaml/#cachekeyfiles).
We're using it in dind-aws, node, php and sonar images.

So no objection for me to remove it from python, and switch it from alpine to slim-buster.

**Comment by Mallear** [comment]
PR Merged today #250
