### ISSUE TITLE
Remove ci-helper from dind-aws

### ISSUE THREAD

**Issue by saugereau** [ekino/docker-buildbox#269]

**Comment by mremi** [comment]
We use it

**Comment by saugereau** [comment]
> We use it

Hi @mremi, can you give us more detail about which case ? 
In my mind the main feature we used was cache management, currently gitlab-ci have this own feature too ...

**Comment by rande** [comment]
No, the state of cache management is not good enough for now.

**Comment by saugereau** [comment]
I add here some information about ci-helper : 
- The current implementation of gitlab-ci allows to do a lot, but still it is not possible to have multiple cache solution per job or artifact per job.
- CI helper has a nice feature, when you tag a commit, the pipeline will save all archives in a specifics path with no deletion policy. So it is very easy to rebuild a docker image (for instance) using code from a previous job
- gitlab ci now support hash computation upfront but only one per job
