### ISSUE TITLE
Migrate to Github container registry

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#334]
Hi,
Considering that the official Docker registry now limits the number of downloads for free users.

https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by Crow-EH** [comment]
Do we really want to switch? I mean, according to [dovker's pricing page](https://www.docker.com/pricing) anonymous are limited to 100 pulls per 6 hours and authenticated users to 200.

I don't think it's a real issue for common users, and "high pull frequency" users just have to use the cache available on their system. I.e For gitlab see https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching

**Comment by axelpavageau** [comment]
I'd like to implement this, just to be on the safe side. Some of our build environments don't have caching mechanisms at the moment, and do a fairly high number of pulls.
