### ISSUE TITLE
Migrate java images to Eclipse Temurin

### ISSUE THREAD

**Issue by clemstoquart** [ekino/docker-buildbox#500]
https://hub.docker.com/_/eclipse-temurin

What do you think ?

**Comment by Crow-EH** [comment]
Switching from adopt to temurin should be the normal thing to do.

Now, we used  debian slim for adopt, while temurin only provide Ubuntu (focal) : That's alright, basic Ubuntu images are already slim downed unlike Debian.

**Comment by Crow-EH** [comment]
We'll need to use a tag supported by dependabot, our current tag is not supported.

Dependabot checked 2 days ago if an update was necessary : https://github.com/ekino/docker-buildbox/network/updates/206730835

It assumed jdk8u282-b08-debian-slim was the latest version, however we only ignore major version updates and the latest version of jdk 8 is jdk8u292-b10-debian-slim on adtopt's docker hub.

We have the same issue with jdk 11.

We might have to use a SHA.

**Comment by clemstoquart** [comment]
@Crow-EH Let's keep this issue for the migration to temurin only and track dependabot related stuff in another one 😉
