### ISSUE TITLE
Switch from awscli v1 to v2

### ISSUE THREAD

**Issue by axelpavageau** [ekino/docker-buildbox#687]

**Comment by swve** [comment]
This is a list of docker images that should be updated, that list will be updated progressively 

- [ ] Node (https://github.com/ekino/docker-buildbox/pull/730) 
- [ ] Kubectl (https://github.com/ekino/docker-buildbox/pull/731)
- [ ] Python
- [ ] PyNode 
- [ ] Terraform
- [ ] Java
- [ ] PHP

**Comment by swve** [comment]
Status for PHP Image  : awscli will be removed from that image in a future update, probably switching to a debian as a base image too

**Comment by axelpavageau** [comment]
thanks a lot for your contribution !
